DROP TABLE IF EXISTS country;

CREATE TABLE country
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title_en    varchar(100) NOT NULL,
    title_ru    varchar(100) NOT NULL,
    currency_id int          REFERENCES currency (id) ON DELETE SET NULL,
    custom      boolean      NOT NULL
);
-- 1
INSERT into country(title_en, title_ru, currency_id, custom)
VALUES ('Russia', 'Россия', 5, false);
-- 2
INSERT into country(title_en, title_ru, currency_id, custom)
VALUES ('Kazakhstan', 'Казахстан', 12, false);
