CREATE TABLE web_user
(
    id       int GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) UNIQUE NOT NULL,
    password varchar             NOT NULL,
    role     varchar(50)         NOT NULL
);

INSERT into web_user(username, "password", "role")
VALUES ('supervisor', '$2a$10$jR.HDbzDdxaoG/QCeRZhHOXnXO0LlJ/mD00hY/7dCdHZ79oY/WUES', 'ROLE_ADMIN');