DROP TABLE IF EXISTS web_user;

CREATE TABLE web_user
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(100) UNIQUE NOT NULL,
    password    varchar             NOT NULL,
    role        varchar(50)         NOT NULL,
    created_at  timestamp           NOT NULL,
    last_active timestamp           NOT NULL,
    active      boolean             NOT NULL
);

INSERT into web_user(username, "password", "role", created_at, last_active, active)
VALUES ('supervisor', '$2a$10$jR.HDbzDdxaoG/QCeRZhHOXnXO0LlJ/mD00hY/7dCdHZ79oY/WUES', 'ROLE_ADMIN', current_timestamp,
        current_timestamp, true);

INSERT into web_user(username, "password", "role", created_at, last_active, active)
VALUES ('Anton-KAS', '$2a$10$jR.HDbzDdxaoG/QCeRZhHOXnXO0LlJ/mD00hY/7dCdHZ79oY/WUES', 'ROLE_ADMIN', current_timestamp,
        current_timestamp, true);