DROP TABLE IF EXISTS account_type;

CREATE TABLE account_type
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title_en varchar(100) NOT NULL,
    title_ru varchar(100) NOT NULL
);

INSERT into account_type(title_en, title_ru)
VALUES ('cash', 'наличные');

INSERT into account_type(title_en, title_ru)
VALUES ('bank', 'банковский');

INSERT into account_type(title_en, title_ru)
VALUES ('credit', 'кредитный');
