DROP TABLE IF EXISTS bank CASCADE;

CREATE TABLE bank
(
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title_en   varchar(100) NOT NULL,
    title_ru   varchar(100) NOT NULL,
    country_id int          REFERENCES country (id) ON DELETE SET NULL,
    custom     boolean      NOT NULL
);

INSERT into bank(title_en, title_ru, country_id, custom)
VALUES ('Tinkoff', 'Тинькофф', 1, false);

INSERT into bank(title_en, title_ru, country_id, custom)
VALUES ('Freedom', 'Фридом', 1, false);

INSERT into bank(title_en, title_ru, country_id, custom)
VALUES ('Freedom', 'Фридом', 2, false);

INSERT into bank(title_en, title_ru, country_id, custom)
VALUES ('Kaspi', 'Каспий', 2, false);
